version: "3.3" # optional since v1.27.0
services:
  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - "8082:8080"
    networks:
      - internal_network

  server:
    image: skynocover/guanda:0.0.6
    restart: always
    networks:
      - internal_network

  web:
    image: skynocover/guandaweb:0.0.3
    restart: always
    networks:
      - internal_network

  man:
    image: webman:latest
    restart: always
    networks:
      - internal_network
    ports:
      - "3000:8080"

networks:
  internal_network:
    driver: bridge
